//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Counselor
    {
        public Counselor()
        {
            this.Appointment = new HashSet<Appointment>();
        }
    
        public int CounselorID { get; set; }
        public string DegreeSuffix { get; set; }
    
        public virtual ICollection<Appointment> Appointment { get; set; }
        public virtual Person Person { get; set; }
    }
}
